### ISSUE TITLE
Funny redirects

### ISSUE THREAD

**Issue by IonicaBizau** [nice-registry/package.land#3]
Since `repos[name]` is being used, something funny happens if we open urls like:

```
/__defineGetter__
--> https://www.npmjs.com/package/function%20__defineGetter__()%20%7B%20[native%20code]%20%7D
```

Because `repos.__defineGetter__` is a native function coming from the `Object` prototype.

I'm not even sure if we need to address this, but just in case. :grin: 

https://github.com/nice-registry/package.land/blob/f4cd43fde4c51b38833316f2f5eea0b994a0117e/server.js#L10-L14

**Comment by hemanth** [comment]
heh, nice catch, `isPrototypeOf` would land to the function,  but `toString` wouldn't, blacklisting them is not a good option but we might decide on what the URL is getting resolved to before redirecting.

**Comment by IonicaBizau** [comment]
Yes, because there is a package named `toString`, while there is no package called `isPrototypeOf`! :joy: 

Maybe using a [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) instead  of a raw object could be a solution.

**Comment by hemanth** [comment]
Yup, that's what I alluded, later there might be an `isPrototypeOf` as well ;)

`Map` seems to be a good choice here.

**Comment by IonicaBizau** [comment]
> Yup, that's what I alluded, later there might be an `isPrototypeOf` as well ;)

Exactly! Actually, the first try was `toString` and was redirecting to GitHub, meaning there is a package already. And I said: *Meh... I have to try something stronger... some function name that would not pass the npm package name validation*. :joy:
